// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  main

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( Note ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* Note ) UnmarshalJSON([]byte) error { return nil }
func ( Note ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* Note ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_Note *Note

func ( NoteList ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* NoteList ) UnmarshalJSON([]byte) error { return nil }
func ( NoteList ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* NoteList ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_NoteList *NoteList
